### 1. (0.2 балла) Реализуйте функцию, возвращающую максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой. Для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответом является 5. Если нулевых элементов нет, функция должна возвращать None.

In [6]:
import numpy as np

def max_element(arr):
    if arr.size < 2:
        return None

    zero_indices = np.where(arr[:-1] == 0)[0]

    if zero_indices.size == 0:
        return None

    return arr[zero_indices + 1].max()

# Тест
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(max_element(x))

5


### 2. (0.2 балла) Реализуйте функцию, принимающую на вход матрицу и некоторое число и возвращающую ближайший к числу элемент матрицы. Например: для X = np.arange(0,10).reshape((2, 5)) и v = 3.6 ответом будет 4.

In [7]:
def nearest_value(X, v):
    return X.flat[np.abs(X - v).argmin()]

X = np.arange(0, 10).reshape((2, 5))
print(nearest_value(X, 3.6))

4


### 3. (0.2 балла) Реализуйте функцию scale(X), которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает выборочное среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на случайной матрице (для её генерации можно использовать, например, функцию numpy.random.randint).

In [8]:
def scale_matrix(X):

    μ = np.mean(X, axis=0)
    σ = np.std(X, axis=0)

    σ = σ + (σ == 0).astype(float)

    return (X - μ) / σ

    np.random.seed(42)
test_matrix = np.random.randint(0, 10, size=(5, 5))
print(test_matrix)
print(scale_matrix(test_matrix))

[[0 1 8 3 2]
 [7 3 6 4 4]
 [5 3 1 5 4]
 [2 3 2 2 3]
 [1 3 9 1 9]]
[[-1.15044748 -2.          0.87843813  0.         -0.99312707]
 [ 1.53392998  0.5         0.25098232  0.70710678 -0.16552118]
 [ 0.76696499  0.5        -1.31765719  1.41421356 -0.16552118]
 [-0.38348249  0.5        -1.00392929 -0.70710678 -0.57932412]
 [-0.76696499  0.5         1.19216603 -1.41421356  1.90349354]]


### 4. (0.2 балла) Реализуйте функцию, которая для заданной матрицы находит:

In [9]:
def matrix_info(X):
    info = {}
    info['det'] = np.linalg.det(X) if X.shape[0] == X.shape[1] else None
    info['trace'] = np.trace(X)
    info['minimum'] = X.min()
    info['maximum'] = X.max()
    info['frobenius_norm'] = np.linalg.norm(X, 'fro')
    info['eigenvalues'] = np.linalg.eigvals(X) if X.shape[0] == X.shape[1] else None
    if X.shape[0] == X.shape[1] and np.linalg.matrix_rank(X) == X.shape[0]:
        info['inv'] = np.linalg.inv(X)
    else:
        info['inv'] = None
    return info

np.random.seed(42)
test_mat = np.random.randn(4, 4)
print(matrix_info(test_mat))

{'det': np.float64(-1.8638200811885155), 'trace': np.float64(-0.7631280259913829), 'minimum': np.float64(-1.913280244657798), 'maximum': np.float64(1.5792128155073915), 'frobenius_norm': np.float64(3.7622616923323706), 'eigenvalues': array([ 1.43750501+0.j        , -0.79407997+0.j        ,
       -0.70327653+1.06686096j, -0.70327653-1.06686096j]), 'inv': array([[-0.33124857, -1.0333483 , -2.21070923, -0.47651024],
       [ 0.12864778, -0.47781825,  0.15271687, -0.43017975],
       [-0.51338817,  0.33588835, -0.8347692 , -0.24072429],
       [ 0.99462192,  0.15079316,  1.08985145,  0.21872535]])}


### 5. (0.2 балла) Повторите 100 раз следующий эксперимент: сгенерируйте две матрицы размера 10×10 из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

In [10]:
np.random.seed(42)
n_experiments = 100
n = 10

max_elements = [np.max(np.random.randn(n, n) @ np.random.randn(n, n))
                for _ in range(n_experiments)]

max_elements = np.array(max_elements)
mean_val = np.mean(max_elements)
quantile_95 = np.percentile(max_elements, 95)

print(f"Среднее значение максимальных элементов: {mean_val:.4f}")
print(f"95-процентная квантиль: {quantile_95:.4f}")

Среднее значение максимальных элементов: 8.4061
95-процентная квантиль: 11.8562


# Авиарейсы в США

## 1. Импорты

In [20]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import Lasso, Ridge
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, KFold
from sklearn.model_selection import cross_val_predict
from sklearn.preprocessing import StandardScaler
%matplotlib inline

## 2. Подгрузка файла

In [21]:
df = pd.read_csv('2008.csv')

## 3. Анализ

### Самая частая причина отмены рейса

In [22]:
cancellation_counts = df['CancellationCode'].value_counts()
print(cancellation_counts)

most_common_cancellation = cancellation_counts.idxmax()
print(f"   Самая частая причина: {most_common_cancellation} (расшифровка: {'Carrier' if most_common_cancellation == 'A' else 'Weather' if most_common_cancellation == 'B' else 'NAS' if most_common_cancellation == 'C' else 'Security'})")

CancellationCode
A    563
B    549
C    299
Name: count, dtype: int64
   Самая частая причина: A (расшифровка: Carrier)


### Расстояние

In [23]:
print(f"Расстояние: среднее={df['Distance'].mean():.2f}, min={df['Distance'].min()}, max={df['Distance'].max()}")

Расстояние: среднее=724.51, min=31, max=4962


In [15]:
min_distance = df['Distance'].min()
min_distance_flights = df[df['Distance'] == min_distance]
print(f"Минимальное расстояние: {min_distance} миль")
print("   Рейсы с таким расстоянием:")
print(f"   Количество таких записей: {len(min_distance_flights)}")
print(f"   Маршруты: {min_distance_flights[['Origin', 'Dest']].drop_duplicates().to_string(index=False)}")
print(f"   Дни (месяц, день месяца, день недели): {min_distance_flights[['Month', 'DayofMonth', 'DayOfWeek']].drop_duplicates().to_string(index=False)}")
print(f"   Номера рейсов: {min_distance_flights[['UniqueCarrier', 'FlightNum']].drop_duplicates().to_string(index=False)}")

# Проверим, какое расстояние было у этих же маршрутов в другие дни
common_routes = min_distance_flights[['Origin', 'Dest']].drop_duplicates()
other_flights_for_route = df.merge(common_routes, on=['Origin', 'Dest'])
other_distances = other_flights_for_route[other_flights_for_route['Distance'] > min_distance]['Distance'].unique()
print(f"   Расстояние на этих маршрутах в другие дни: {sorted(other_distances)[:5]} миль (первые 5 уникальных значений)")

Минимальное расстояние: 31 миль
   Рейсы с таким расстоянием:
   Количество таких записей: 6
   Маршруты: Origin Dest
   WRG  PSG
   PSG  WRG
   Дни (месяц, день месяца, день недели):  Month  DayofMonth  DayOfWeek
    12          30          2
    12          26          5
     8          18          1
     3          11          2
     8           9          6
     2          28          4
   Номера рейсов: UniqueCarrier  FlightNum
           AS         65
           AS         64
   Расстояние на этих маршрутах в другие дни: [] миль (первые 5 уникальных значений)


### Аэропорт с наибольшим числом вылетов

In [24]:
origin_counts = df['Origin'].value_counts()
top_airport = origin_counts.idxmax()
top_count = origin_counts.iloc[0]
print(f"   Код аэропорта: {top_airport}")
print(f"   Количество вылетов: {top_count}")

   Код аэропорта: ATL
   Количество вылетов: 4134


### Среднее время полета по аэропортам вылета

In [26]:
avg_airtime_by_origin = df.groupby('Origin')['AirTime'].mean().sort_values(ascending=False)
top_airport_airtime = avg_airtime_by_origin.idxmax()
top_airtime_value = avg_airtime_by_origin.iloc[0]
print(f"   Аэропорт с наибольшим средним временем полета: {top_airport_airtime}")
print(f"   Среднее время полета: {top_airtime_value:.2f} минут")

   Аэропорт с наибольшим средним временем полета: SJU
   Среднее время полета: 205.20 минут


### Аэропорт с наибольшей долей задержанных рейсов (с фильтром N >= 1000)

In [27]:
dep_delay_stats = df.groupby('Origin').agg(
    total_flights=('DepDelay', 'count'),
    delayed_flights=('DepDelay', lambda x: (x > 0).sum())
)

dep_delay_stats_filtered = dep_delay_stats.loc[dep_delay_stats['total_flights'] >= 1000].copy()
dep_delay_stats_filtered = dep_delay_stats_filtered.assign(
    delay_rate=dep_delay_stats_filtered['delayed_flights'] / dep_delay_stats_filtered['total_flights']
)
max_delay_airport = dep_delay_stats_filtered['delay_rate'].idxmax()
max_delay_rate = dep_delay_stats_filtered['delay_rate'].max()
print(f"   Аэропорт: {max_delay_airport}")
print(f"   Доля задержанных рейсов: {max_delay_rate:.3f}")
print(f"   Всего рейсов из этого аэропорта: {dep_delay_stats_filtered.loc[max_delay_airport, 'total_flights']}")
print(f"   Задержанных рейсов: {dep_delay_stats_filtered.loc[max_delay_airport, 'delayed_flights']}")

   Аэропорт: EWR
   Доля задержанных рейсов: 0.529
   Всего рейсов из этого аэропорта: 1343
   Задержанных рейсов: 710
